name: CD Fake
on:
  workflow_dispatch:
jobs:
  deploy-fake:
    runs-on: ubuntu-latest
    steps:
      - name: Fake de deploy ambiente
        run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
